/** @type {import("next").NextConfig} */
const config = {
  reactStrictMode: true,
  // typedRoutes intentionally disabled: it makes standalone `tsc --noEmit`
  // fail against a route manifest only generated by build/dev.
};

export default config;
